server:
  error:
    include-message: always

spring:
  profiles:
    active: ${APP_ENV:dev}
  application:
    name: Knowledge Tests
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SECURITY_JWK_URI}